version: '3'

services:
  db:
    image: library/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
    ports:
     - "5432:5432"
volumes:
  postgres-data: